### ISSUE TITLE
language independent 

### ISSUE THREAD

**Issue by MAnal0025** [MTG/WGANSing#15]
hi 
I want to implement your model using another language corpus so I want to ask you that is your model is language-dependent or independent? 
thanks in advance

**Comment by ghost** [comment]
All is in the paper : [WGANSing: A Multi-Voice Singing VoiceSynthesizer Based on the Wasserstein-GAN](https://arxiv.org/pdf/1903.10729.pdf) and in [The NUS sung and spoken lyrics corpus: A quantitative comparison of singing and speech](https://www.researchgate.net/publication/261277428_The_NUS_sung_and_spoken_lyrics_corpus_A_quantitative_comparison_of_singing_and_speech)

The process use the **NUS** database that use a subset of the **ARPABET** phonemes that is common in the [CMU Pronouncing Dictionary](http://www.speech.cs.cmu.edu/cgi-bin/cmudict). The CMU dictionary is **US English** based but you can easily adapt the system for a more generic phonetic system like [IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet). [ARPABET](https://en.wikipedia.org/wiki/ARPABET) is a subset of IPA and is interchangeable.
