### ISSUE TITLE
variable max_phr_len in config.py

### ISSUE THREAD

**Issue by deblinbagchi** [MTG/WGANSing#21]
I am trying to use the GAN toolkit to generate read speech. I am currently trying to understand your code. It would really help if you tell me what is the role of the variable `max_phr_len` in `config.py` ? I see the value is set to 128. What would happen if I increase or decrease that value ? I have been reading your paper but can't seem to understand.

**Comment by pc2752** [comment]
Hi, the variable max_phr_len in config refers to the maximum length of the input features (in time) used for training the network. It can be increased or decreased according to the dataset you have in ming, but you might also need to adjust the variable `encoder_layers` to account for the change in the length (eg: if you change the `max_phr_len` to 64, you could also decrease the `encoder_layers` to 6
