### ISSUE TITLE
Encounter error while synthesizing: "a mismatch between the current graph and the graph"

### ISSUE THREAD

**Issue by the-seekers-project** [MTG/WGANSing#5]
Hi,

I am trying to run the trained model by following the instructions to synthesize a file. I was able to setup the dataset. But when i am running main.py, it fails while restoring from a checkpoint with the following error:

line 1322, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that
 you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [3,64] rhs shape= [12,64]
         [[node save/Assign_177 (defined at D:\GT_Robotic Musicianship\Voice Synthesis\Multi_Voice_Sing_Speak_Sing-master\models.py:59) ]]

The code includes a comment saying: 
      # There is a mismatch between the graph and the checkpoint being loaded.
      # We add a more reasonable error message here to help users (b/110263146)

Could you please help me understand how to get around this error?

Thank you!

**Comment by pc2752** [comment]
Hi, 
This error usually occurs if there is a mismatch between the code and the graph in the checkpoint. Perhaps you haave made a change in the code or do not have the latest version.  Could you try a git pull to get the latest version of the code and the latest version of the model from the link in https://github.com/MTG/WGANSing.

Thanks
